name: Pull Request Workflow

on:
  pull_request:
    branches:
      - master #current latest version
      - "v[1-9][0-9]+.x" #release branches with previous releases
      - "v[1-9][0-9]+-next" #next release branches

jobs:
  test-job:
    name: "Test job"
    runs-on: "ubuntu-latest"
    steps:
      - name: Test step
        run: exit 1
