name: Publish to Github Package Registry
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      newPackageJsonVersion:
        description: "The semver for the version you would like to publish"
        required: true
      releaseTitle:
        description: "A short description to describe the release (do NOT include the version number here)"

jobs:
  # prepare-job:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions-ecosystem/action-regex-match@v2
  #       id: regex-match
  #       with:
  #         text: ${{ github.ref_name }}
  #         regex: '^(master)|(v[1-9][0-9]*\.x)$'
  #     - name: Test step 1
  #       if: ${{ steps.regex-match.outputs.match == '' }}
  #       run: |
  #         echo "${{ github.ref_name }} branch is not allowed to perform publish workflow"
  #         exit 1
  #     - name: Test step 2
  #       run: echo "Test step run"
  branch-check:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.ref_name, 'release/') || github.ref_name != 'master' }}
    steps:
      - run: |
          echo "${{ github.ref_name }} branch is not allowed to perform publish workflow"
          exit 1
  main-job:
    runs-on: ubuntu-latest
    needs: branch-check
    steps:
      - name: Test step 1
        run: echo "Test step run"
      - name: Test step 2
        run: echo "Test step run"
  last-job:
    runs-on: ubuntu-latest
    needs: main-job
    steps:
      - name: Test step 1
        run: echo "Test step run"
      - name: Test step 2
        run: echo "Test step run"
